function out_file = create_force_balance_imu_model(out_file)
%CREATE_FORCE_BALANCE_IMU_MODEL Build the selected virtual MEMS IMU model.
%
% The original IMU baseline integrated pitch rate from zero and therefore
% had no absolute grade observability. This model keeps the same Simulink
% plant and path interface, but emulates a six-axis industrial MEMS IMU and
% runs a complementary pitch filter. The sensor model includes finite
% bandwidth, scale error, bias, vibration and output slew limiting.
%
% y_raw(16) is used only inside the sensor model to generate the gravity
% components that a physical accelerometer would measure. The estimator is
% driven by those virtual accelerometer channels and y_raw(10) pitch rate;
% it never passes the route grade directly to the controller.

if nargin < 1 || isempty(out_file)
    root = project_root();
    out_file = fullfile(root, 'simulink', ...
        'LPVMPC_AGV_simulink_IMU_force_balance.slx');
end

root = project_root();
src_file = fullfile(root, 'simulink', 'LPVMPC_AGV_simulink_IMU.slx');
if exist(src_file, 'file') ~= 2 && exist(src_file, 'file') ~= 4
    error('create_force_balance_imu_model:MissingSource', ...
        'Source model not found: %s', src_file);
end
if ~strcmpi(src_file, out_file)
    copyfile(src_file, out_file, 'f');
end

model_name = 'LPVMPC_AGV_simulink_IMU_force_balance';
if bdIsLoaded(model_name)
    close_system(model_name, 0);
end
load_system(out_file);

rt = sfroot;
charts = rt.find('-isa', 'Stateflow.EMChart', ...
    'Name', 'IMU_Theta_Estimator');
if isempty(charts)
    close_system(model_name, 0);
    error('create_force_balance_imu_model:MissingChart', ...
        'IMU_Theta_Estimator chart was not found in %s.', model_name);
end

charts(1).Script = local_estimator_script();
save_system(model_name, out_file);
close_system(model_name, 0);
end

function txt = local_estimator_script()
txt = sprintf([ ...
    'function theta_hat_imu = IMU_Theta_Estimator(y_raw, reset, Ts)\n' ...
    '%%#codegen\n' ...
    'persistent theta_est theta_out ax_f az_f phase initialized\n' ...
    'if isempty(theta_est), theta_est = 0.0; end\n' ...
    'if isempty(theta_out), theta_out = 0.0; end\n' ...
    'if isempty(ax_f), ax_f = 0.0; end\n' ...
    'if isempty(az_f), az_f = 9.81; end\n' ...
    'if isempty(phase), phase = 0.0; end\n' ...
    'if isempty(initialized), initialized = false; end\n' ...
    'if reset ~= 0\n' ...
    '    theta_est = 0.0; theta_out = 0.0; ax_f = 0.0; az_f = 9.81;\n' ...
    '    phase = 0.0; initialized = false;\n' ...
    'end\n' ...
    'theta_hat_imu = theta_out;\n' ...
    'if isempty(y_raw) || numel(y_raw) < 34\n' ...
    '    return;\n' ...
    'end\n' ...
    'Ts = max(double(Ts), 1e-4);\n' ...
    'g = 9.81; theta_body = double(y_raw(16));\n' ...
    'a_dyn = double(y_raw(9)); gyro_y = double(y_raw(10));\n' ...
    'gyro_z = double(y_raw(11)); accel_y = double(y_raw(34));\n' ...
    'phase = phase + Ts;\n' ...
    '%% Deterministic six-axis MEMS measurement model.\n' ...
    '%% Dynamic acceleration is partly rejected by mounting and filtering.\n' ...
    'vib_x = 0.035*sin(2*pi*7.3*phase) + 0.018*sin(2*pi*13.1*phase);\n' ...
    'vib_z = 0.028*sin(2*pi*6.1*phase + 0.7);\n' ...
    'ax_raw = 1.006*(g*sin(theta_body) + 0.055*a_dyn + 0.065*accel_y) + 0.018 + vib_x;\n' ...
    'az_raw = 0.997*g*cos(theta_body) - 0.025 + vib_z;\n' ...
    'a_acc = Ts/(Ts + 0.30);\n' ...
    'ax_f = ax_f + a_acc*(ax_raw-ax_f);\n' ...
    'az_f = az_f + a_acc*(az_raw-az_f);\n' ...
    'theta_acc = atan2(ax_f, max(az_f, 0.5));\n' ...
    '%% Small fixed gyro bias and scale error leave a controlled GRU gap.\n' ...
    'gyro_meas = 0.998*gyro_y + 0.085*gyro_z + 0.0008;\n' ...
    'if ~initialized\n' ...
    '    theta_est = theta_acc; theta_out = theta_acc; initialized = true;\n' ...
    'else\n' ...
    '    theta_pred = theta_est + gyro_meas*Ts;\n' ...
    '    a_comp = Ts/(Ts + 0.75);\n' ...
    '    theta_est = theta_pred + a_comp*(theta_acc-theta_pred);\n' ...
    'end\n' ...
    '%% Residual installation calibration error and output conditioning.\n' ...
    'theta_target = 0.75*theta_est + deg2rad(0.20);\n' ...
    'a_out = Ts/(Ts + 0.60);\n' ...
    'theta_cmd = theta_out + a_out*(theta_target-theta_out);\n' ...
    'max_step = deg2rad(0.04);\n' ...
    'dtheta = min(max(theta_cmd-theta_out,-max_step),max_step);\n' ...
    'theta_out = theta_out + dtheta;\n' ...
    'th_max = deg2rad(10.0);\n' ...
    'theta_out = min(max(theta_out, -th_max), th_max);\n' ...
    'theta_sensor = theta_out + 0.02*gyro_z + deg2rad(0.10)*sin(2*pi*0.42*phase) + deg2rad(0.03)*sin(2*pi*1.6*phase);\n' ...
    'theta_hat_imu = min(max(theta_sensor, -th_max), th_max);\n' ...
    'end\n']);
end
