classdef ConvLayer1053 < nnet.layer.Layer & nnet.layer.Formattable
    % A custom layer auto-generated while importing an ONNX network.

    %#codegen
    %#ok<*PROPLC>
    %#ok<*NBRAK>
    %#ok<*INUSL>
    %#ok<*VARARG>

    properties (Learnable)
        onnx__Conv_192
        onnx__Conv_193
    end

    properties
        ONNXParams         % An ONNXParameters object containing parameters used by this layer.
    end

    methods
        function this = ConvLayer1053(name, onnxParams)
            this.Name = name;
            this.OutputNames = {'x_blocks_2_depthwise'};
            this.ONNXParams = onnxParams;
            this.onnx__Conv_192 = onnxParams.Learnables.onnx__Conv_192;
            this.onnx__Conv_193 = onnxParams.Learnables.onnx__Conv_193;
        end

        function [x_blocks_2_depthwise] = predict(this, x_blocks_1_Add_outpu)
            if isdlarray(x_blocks_1_Add_outpu)
                x_blocks_1_Add_outpu = stripdims(x_blocks_1_Add_outpu);
            end
            x_blocks_1_Add_outpuNumDims = 3;
            onnxParams = this.ONNXParams;
            onnxParams.Learnables.onnx__Conv_192 = this.onnx__Conv_192;
            onnxParams.Learnables.onnx__Conv_193 = this.onnx__Conv_193;
            [x_blocks_2_depthwise, x_blocks_2_depthwiseNumDims] = ConvFcn(x_blocks_1_Add_outpu, x_blocks_1_Add_outpuNumDims, onnxParams, 'Training', false, ...
                'InputDataPermutation', {[2 1 3], ['as-is']}, ...
                'OutputDataPermutation', {[2 1 3], ['as-is']});
            if any(cellfun(@(A)~isnumeric(A) && ~islogical(A), {x_blocks_2_depthwise}))
                fprintf('Runtime error in network. At least one output of custom layer ''%s'' is a non-numeric, non-logical value.\n', 'ConvLayer1053');
                error(message('nnet_cnn_onnx:onnx:BadCustomLayerRuntimeOutput', 'ConvLayer1053'));
            end
            x_blocks_2_depthwise = dlarray(single(x_blocks_2_depthwise), 'CBT');
            if ~coder.target('MATLAB')
                x_blocks_2_depthwise = extractdata(x_blocks_2_depthwise);
            end
        end

        function [x_blocks_2_depthwise] = forward(this, x_blocks_1_Add_outpu)
            if isdlarray(x_blocks_1_Add_outpu)
                x_blocks_1_Add_outpu = stripdims(x_blocks_1_Add_outpu);
            end
            x_blocks_1_Add_outpuNumDims = 3;
            onnxParams = this.ONNXParams;
            onnxParams.Learnables.onnx__Conv_192 = this.onnx__Conv_192;
            onnxParams.Learnables.onnx__Conv_193 = this.onnx__Conv_193;
            [x_blocks_2_depthwise, x_blocks_2_depthwiseNumDims] = ConvFcn(x_blocks_1_Add_outpu, x_blocks_1_Add_outpuNumDims, onnxParams, 'Training', true, ...
                'InputDataPermutation', {[2 1 3], ['as-is']}, ...
                'OutputDataPermutation', {[2 1 3], ['as-is']});
            if any(cellfun(@(A)~isnumeric(A) && ~islogical(A), {x_blocks_2_depthwise}))
                fprintf('Runtime error in network. At least one output of custom layer ''%s'' is a non-numeric, non-logical value.\n', 'ConvLayer1053');
                error(message('nnet_cnn_onnx:onnx:BadCustomLayerRuntimeOutput', 'ConvLayer1053'));
            end
            x_blocks_2_depthwise = dlarray(single(x_blocks_2_depthwise), 'CBT');
            if ~coder.target('MATLAB')
                x_blocks_2_depthwise = extractdata(x_blocks_2_depthwise);
            end
        end
    end
end

function [x_blocks_2_depthwise, x_blocks_2_depthwiseNumDims, state] = ConvFcn(x_blocks_1_Add_outpu, x_blocks_1_Add_outpuNumDims, params, varargin)
%CONVFCN Function implementing an imported ONNX network.
%
% THIS FILE WAS AUTO-GENERATED BY importONNXFunction.
% ONNX Operator Set Version: 17
%
% Variable names in this function are taken from the original ONNX file.
%
% [X_BLOCKS_2_DEPTHWISE] = ConvFcn(X_BLOCKS_1_ADD_OUTPU, PARAMS)
%			- Evaluates the imported ONNX network CONVFCN with input(s)
%			X_BLOCKS_1_ADD_OUTPU and the imported network parameters in PARAMS. Returns
%			network output(s) in X_BLOCKS_2_DEPTHWISE.
%
% [X_BLOCKS_2_DEPTHWISE, STATE] = ConvFcn(X_BLOCKS_1_ADD_OUTPU, PARAMS)
%			- Additionally returns state variables in STATE. When training,
%			use this form and set TRAINING to true.
%
% [__] = ConvFcn(X_BLOCKS_1_ADD_OUTPU, PARAMS, 'NAME1', VAL1, 'NAME2', VAL2, ...)
%			- Specifies additional name-value pairs described below:
%
% 'Training'
% 			Boolean indicating whether the network is being evaluated for
%			prediction or training. If TRAINING is true, state variables
%			will be updated.
%
% 'InputDataPermutation'
%			'auto' - Automatically attempt to determine the permutation
%			 between the dimensions of the input data and the dimensions of
%			the ONNX model input. For example, the permutation from HWCN
%			(MATLAB standard) to NCHW (ONNX standard) uses the vector
%			[4 3 1 2]. See the documentation for IMPORTONNXFUNCTION for
%			more information about automatic permutation.
%
%			'none' - Input(s) are passed in the ONNX model format. See 'Inputs'.
%
%			numeric vector - The permutation vector describing the
%			transformation between input data dimensions and the expected
%			ONNX input dimensions.%
%			cell array - If the network has multiple inputs, each cell
%			contains 'auto', 'none', or a numeric vector.
%
% 'OutputDataPermutation'
%			'auto' - Automatically attempt to determine the permutation
%			between the dimensions of the output and a conventional MATLAB
%			dimension ordering. For example, the permutation from NC (ONNX
%			standard) to CN (MATLAB standard) uses the vector [2 1]. See
%			the documentation for IMPORTONNXFUNCTION for more information
%			about automatic permutation.
%
%			'none' - Return output(s) as given by the ONNX model. See 'Outputs'.
%
%			numeric vector - The permutation vector describing the
%			transformation between the ONNX output dimensions and the
%			desired output dimensions.%
%			cell array - If the network has multiple outputs, each cell
%			contains 'auto', 'none' or a numeric vector.
%
% Inputs:
% -------
% X_BLOCKS_1_ADD_OUTPU
%			- Input(s) to the ONNX network.
%			  The input size(s) expected by the ONNX file are:
%				  X_BLOCKS_1_ADD_OUTPU:		[Unknown, Unknown, Unknown]				Type: FLOAT
%			  By default, the function will try to permute the input(s)
%			  into this dimension ordering. If the default is incorrect,
%			  use the 'InputDataPermutation' argument to control the
%			  permutation.
%
%
% PARAMS	- Network parameters returned by 'importONNXFunction'.
%
%
% Outputs:
% --------
% X_BLOCKS_2_DEPTHWISE
%			- Output(s) of the ONNX network.
%			  Without permutation, the size(s) of the outputs are:
%				  X_BLOCKS_2_DEPTHWISE:		[Unknown, Unknown, Unknown]				Type: FLOAT
%			  By default, the function will try to permute the output(s)
%			  from this dimension ordering into a conventional MATLAB
%			  ordering. If the default is incorrect, use the
%			  'OutputDataPermutation' argument to control the permutation.
%
% STATE		- (Optional) State variables. When TRAINING is true, these will
% 			  have been updated from the original values in PARAMS.State.
%
%
%  See also importONNXFunction

% Preprocess the input data and arguments:
[x_blocks_1_Add_outpu, Training, outputDataPerms, anyDlarrayInputs] = preprocessInput(x_blocks_1_Add_outpu, params, varargin{:});
% Put all variables into a single struct to implement dynamic scoping:
[Vars, NumDims] = packageVariables(params, {'x_blocks_1_Add_outpu'}, {x_blocks_1_Add_outpu}, [x_blocks_1_Add_outpuNumDims]);
% Call the top-level graph function:
[x_blocks_2_depthwise, x_blocks_2_depthwiseNumDims, state] = ConvGraph1047(x_blocks_1_Add_outpu, NumDims.x_blocks_1_Add_outpu, Vars, NumDims, Training, params.State);
% Postprocess the output data
[x_blocks_2_depthwise] = postprocessOutput(x_blocks_2_depthwise, outputDataPerms, anyDlarrayInputs, Training, varargin{:});
end

function [x_blocks_2_depthwise, x_blocks_2_depthwiseNumDims1052, state] = ConvGraph1047(x_blocks_1_Add_outpu, x_blocks_1_Add_outpuNumDims1051, Vars, NumDims, Training, state)
% Function implementing the graph 'ConvGraph1047'
% Update Vars and NumDims from the graph's formal input parameters. Note that state variables are already in Vars.
Vars.x_blocks_1_Add_outpu = x_blocks_1_Add_outpu;
NumDims.x_blocks_1_Add_outpu = x_blocks_1_Add_outpuNumDims1051;

% Execute the operators:
% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.x_blocks_2_depthwise] = prepareConvArgs(Vars.onnx__Conv_192, Vars.onnx__Conv_193, Vars.ConvStride1048, Vars.ConvDilationFactor1049, Vars.ConvPadding1050, 64, NumDims.x_blocks_1_Add_outpu, NumDims.onnx__Conv_192);
Vars.x_blocks_2_depthwise = dlconv(Vars.x_blocks_1_Add_outpu, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Set graph output arguments from Vars and NumDims:
x_blocks_2_depthwise = Vars.x_blocks_2_depthwise;
x_blocks_2_depthwiseNumDims1052 = NumDims.x_blocks_2_depthwise;
% Set output state from Vars:
state = updateStruct(state, Vars);
end

function [inputDataPerms, outputDataPerms, Training] = parseInputs(x_blocks_1_Add_outpu, numDataOutputs, params, varargin)
% Function to validate inputs to ConvFcn:
p = inputParser;
isValidArrayInput = @(x)isnumeric(x) || isstring(x);
isValidONNXParameters = @(x)isa(x, 'ONNXParameters');
addRequired(p, 'x_blocks_1_Add_outpu', isValidArrayInput);
addRequired(p, 'params', isValidONNXParameters);
addParameter(p, 'InputDataPermutation', 'auto');
addParameter(p, 'OutputDataPermutation', 'auto');
addParameter(p, 'Training', false);
parse(p, x_blocks_1_Add_outpu, params, varargin{:});
inputDataPerms = p.Results.InputDataPermutation;
outputDataPerms = p.Results.OutputDataPermutation;
Training = p.Results.Training;
if isnumeric(inputDataPerms)
    inputDataPerms = {inputDataPerms};
end
if isstring(inputDataPerms) && isscalar(inputDataPerms) || ischar(inputDataPerms)
    inputDataPerms = repmat({inputDataPerms},1,1);
end
if isnumeric(outputDataPerms)
    outputDataPerms = {outputDataPerms};
end
if isstring(outputDataPerms) && isscalar(outputDataPerms) || ischar(outputDataPerms)
    outputDataPerms = repmat({outputDataPerms},1,numDataOutputs);
end
end

function [x_blocks_1_Add_outpu, Training, outputDataPerms, anyDlarrayInputs] = preprocessInput(x_blocks_1_Add_outpu, params, varargin)
% Parse input arguments
[inputDataPerms, outputDataPerms, Training] = parseInputs(x_blocks_1_Add_outpu, 1, params, varargin{:});
anyDlarrayInputs = any(cellfun(@(x)isa(x, 'dlarray'), {x_blocks_1_Add_outpu}));
% Make the input variables into unlabelled dlarrays:
x_blocks_1_Add_outpu = makeUnlabeledDlarray(x_blocks_1_Add_outpu);
% Permute inputs if requested:
x_blocks_1_Add_outpu = permuteInputVar(x_blocks_1_Add_outpu, inputDataPerms{1}, 3);
end

function [x_blocks_2_depthwise] = postprocessOutput(x_blocks_2_depthwise, outputDataPerms, anyDlarrayInputs, Training, varargin)
% Set output type:
if ~anyDlarrayInputs && ~Training
    if isdlarray(x_blocks_2_depthwise)
        x_blocks_2_depthwise = extractdata(x_blocks_2_depthwise);
    end
end
% Permute outputs if requested:
x_blocks_2_depthwise = permuteOutputVar(x_blocks_2_depthwise, outputDataPerms{1}, 3);
end


%% dlarray functions implementing ONNX operators:

function [weights, bias, stride, dilationFactor, padding, dataFormat, numDimsY] = prepareConvArgs(...
    weights, bias, stride, dilationFactor, padding, numWtGroups, numDimsX, numDimsW)
% Prepares arguments for implementing the ONNX Conv operator

%   Copyright 2020 The MathWorks, Inc.

% Weights: The ONNX weight dim is Fcxyz..., where c=C/G, G is numGroups,
% and xyz... are spatial dimensions. DLT "weights" here is the flip of
% that, or ...zyxcF. dlconv requires ...zyxcfG, where f=F/G. So reshape to
% split the last dimension.
sizeW    = size(weights, 1:numDimsW);
F        = sizeW(end);
newWSize = [sizeW(1:numDimsW-1), F/numWtGroups, numWtGroups];
weights  = reshape(weights, newWSize);
% bias
if isempty(bias)
    bias = 0;
end
bias = dlarray(bias(:),'CU');
% Derive missing default attributes from weight tensor
numSpatialDims = numDimsW-2;
if isempty(padding)
    padding = zeros(1, 2*numSpatialDims);
end
if isempty(stride)
    stride = ones(1,numSpatialDims);
end
if isempty(dilationFactor)
    dilationFactor = ones(1,numSpatialDims);
end
% Make the attributes non-dlarrays:
if isa(stride, 'dlarray')
    stride = extractdata(stride);
end
if isa(dilationFactor, 'dlarray')
    dilationFactor = extractdata(dilationFactor);
end
if isa(padding, 'dlarray')
    padding = extractdata(padding);
end
% Make the attributes double row vectors, and flip their dimension ordering
% to reverse-onnx:
stride = fliplr(double(stride(:)'));
dilationFactor = fliplr(double(dilationFactor(:)'));
if isnumeric(padding)       % padding can be "same"
    % ONNX: [x1_begin, ..., xn_begin, x1_end, ...,xn_end]
    % DLT:  [xn_begin, ..., x1_begin;
    %        xn_end, ..., x1_end]       (Note the lrflip and semicolon)
    padding = fliplr(transpose(reshape(padding, [], 2)));
end
% Set dataformat and numdims
dataFormat = [repmat('S', 1, numDimsX-2) 'CB'];
numDimsY = numDimsX;
end

%% Utility functions:

function s = appendStructs(varargin)
% s = appendStructs(s1, s2,...). Assign all fields in s1, s2,... into s.

%   Copyright 2020 The MathWorks, Inc.

if isempty(varargin)
    s = struct;
else
    s = varargin{1};
    for i = 2:numel(varargin)
        fromstr = varargin{i};
        fs = fieldnames(fromstr);
        for j = 1:numel(fs)
            s.(fs{j}) = fromstr.(fs{j});
        end
    end
end
end

function checkInputSize(inputShape, expectedShape, inputName)

%   Copyright 2020-2021 The MathWorks, Inc.

if numel(expectedShape)==0
    % The input is a scalar
    if ~isequal(inputShape, [1 1])
        inputSizeStr = makeSizeString(inputShape);
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, "[1,1]", inputSizeStr));
    end
elseif numel(expectedShape)==1
    % The input is a vector
    if ~shapeIsColumnVector(inputShape) || ~iSizesMatch({inputShape(1)}, expectedShape)
        expectedShape{2} = 1;
        expectedSizeStr = makeSizeString(expectedShape);
        inputSizeStr = makeSizeString(inputShape);
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, expectedSizeStr, inputSizeStr));
    end
else
    % The input has 2 dimensions or more

    % The input dimensions have been reversed; flip them back to compare to the
    % expected ONNX shape.
    inputShape = fliplr(inputShape);

    % If the expected shape has fewer dims than the input shape, error.
    if numel(expectedShape) < numel(inputShape)
        expectedSizeStr = strjoin(["[", strjoin(string(expectedShape), ","), "]"], "");
        error(message('nnet_cnn_onnx:onnx:InputHasGreaterNDims', inputName, expectedSizeStr));
    end

    % Prepad the input shape with trailing ones up to the number of elements in
    % expectedShape
    inputShape = num2cell([ones(1, numel(expectedShape) - length(inputShape)) inputShape]);

    % Find the number of variable size dimensions in the expected shape
    numVariableInputs = sum(cellfun(@(x) isa(x, 'char') || isa(x, 'string'), expectedShape));

    % Find the number of input dimensions that are not in the expected shape
    % and cannot be represented by a variable dimension
    nonMatchingInputDims = setdiff(string(inputShape), string(expectedShape));
    numNonMatchingInputDims  = numel(nonMatchingInputDims) - numVariableInputs;

    expectedSizeStr = makeSizeString(expectedShape);
    inputSizeStr = makeSizeString(inputShape);
    if numNonMatchingInputDims == 0 && ~iSizesMatch(inputShape, expectedShape)
        % The actual and expected input dimensions match, but in
        % a different order. The input needs to be permuted.
        error(message('nnet_cnn_onnx:onnx:InputNeedsPermute',inputName, expectedSizeStr, inputSizeStr));
    elseif numNonMatchingInputDims > 0
        % The actual and expected input sizes do not match.
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, expectedSizeStr, inputSizeStr));
    end
end
end

function doesMatch = iSizesMatch(inputShape, expectedShape)
% Check whether the input and expected shapes match, in order.
% Size elements match if (1) the elements are equal, or (2) the expected
% size element is a variable (represented by a character vector or string)
doesMatch = true;
for i=1:numel(inputShape)
    if ~(isequal(inputShape{i},expectedShape{i}) || ischar(expectedShape{i}) || isstring(expectedShape{i}))
        doesMatch = false;
        return
    end
end
end

function sizeStr = makeSizeString(shape)
sizeStr = strjoin(["[", strjoin(string(shape), ","), "]"], "");
end

function isVec = shapeIsColumnVector(shape)
if numel(shape) == 2 && shape(2) == 1
    isVec = true;
else
    isVec = false;
end
end
function X = makeUnlabeledDlarray(X)
% Make numeric X into an unlabelled dlarray

%   Copyright 2020-2021 The MathWorks, Inc.

if isa(X, 'dlarray')
    X = stripdims(X);
elseif isnumeric(X)
    if isinteger(X)
        % Make ints double so they can combine with anything without
        % reducing precision
        X = double(X);
    end
    X = dlarray(X);
end
end

function [Vars, NumDims] = packageVariables(params, inputNames, inputValues, inputNumDims)

%   Copyright 2020 The MathWorks, Inc.

% inputNames, inputValues are cell arrays. inputRanks is a numeric vector.
Vars = appendStructs(params.Learnables, params.Nonlearnables, params.State);
NumDims = params.NumDimensions;
% Add graph inputs
for i = 1:numel(inputNames)
    Vars.(inputNames{i}) = inputValues{i};
    NumDims.(inputNames{i}) = inputNumDims(i);
end
end

function X = permuteInputVar(X, userDataPerm, onnxNDims)

%   Copyright 2020-2021 The MathWorks, Inc.
% Returns reverse-ONNX ordering
if onnxNDims == 0
    return;
elseif onnxNDims == 1 && isvector(X)
    X = X(:);
    return;
elseif isnumeric(userDataPerm)
    % Permute into reverse ONNX ordering
    if numel(userDataPerm) ~= onnxNDims
        error(message('nnet_cnn_onnx:onnx:InputPermutationSize', numel(userDataPerm), onnxNDims));
    end
    perm = fliplr(userDataPerm);
elseif isequal(userDataPerm, 'auto') && onnxNDims == 4
    % Permute MATLAB HWCN to reverse onnx (WHCN)
    perm = [2 1 3 4];
elseif isequal(userDataPerm, 'as-is')
    % Do not permute the input
    perm = 1:ndims(X);
else
    % userDataPerm is either 'none' or 'auto' with no default, which means
    % it's already in onnx ordering, so just make it reverse onnx
    perm = max(2,onnxNDims):-1:1;
end
X = permute(X, perm);
end

function Y = permuteOutputVar(Y, userDataPerm, onnxNDims)

%   Copyright 2020-2021 The MathWorks, Inc.
switch onnxNDims
    case 0
        perm = [];
    case 1
        if isnumeric(userDataPerm)
            % Use the user's permutation because Y is a column vector which
            % already matches ONNX.
            perm = userDataPerm;
        elseif isequal(userDataPerm, 'auto')
            % Treat the 1D onnx vector as a 2D column and transpose it
            perm = [2 1];
        else
            % userDataPerm is 'none'. Leave Y alone because it already
            % matches onnx.
            perm = [];
        end
    otherwise
        % ndims >= 2
        if isnumeric(userDataPerm)
            % Use the inverse of the user's permutation. This is not just the
            % flip of the permutation vector.
            perm = onnxNDims + 1 - userDataPerm;
        elseif isequal(userDataPerm, 'auto')
            if onnxNDims == 2
                % Permute reverse ONNX CN to DLT CN (do nothing)
                perm = [];
            elseif onnxNDims == 4
                % Permute reverse onnx (WHCN) to MATLAB HWCN
                perm = [2 1 3 4];
            else
                % User wants the output in ONNX ordering, so just reverse it from
                % reverse onnx
                perm = onnxNDims:-1:1;
            end
        elseif isequal(userDataPerm, 'as-is')
            % Do not permute the input
            perm = 1:ndims(Y);
        else
            % userDataPerm is 'none', so just make it reverse onnx
            perm = onnxNDims:-1:1;
        end
end
if ~isempty(perm)
    Y = permute(Y, perm);
end
end

function s = updateStruct(s, t)
% Set all existing fields in s from fields in t, ignoring extra fields in
% t.
%   Copyright 2020 The MathWorks, Inc.

for name = transpose(fieldnames(s))
    s.(name{1}) = t.(name{1});
end
end
